# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"